name: Literal
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep 'LITERAL_'
        env:
          LITERAL_NULL : ${{ null }} #null型
          LITERAL_BOOLEAN : ${{ true }} #boolean型
          LITERAL_NUMBER : ${{ 1919 }} #number型
          LITERAL_STRING : ${{ 'hogehoge' }} #string型(通常記法)
          LITERAL_omit_STRING : abcde #string型(省略記法)
  
      